import type { QueryOptions, RunEvent, RunRecord } from "@perch/protocol";
import type { CallOptions, Transport } from "./http";
import { readNdjson } from "./ndjson";

/** The body both query routes take. `runId` is generated by the server when left out. */
export type RunInput = Partial<QueryOptions> & {
  connectionId: string;
  sql: string;
  /** Purely informational; the server defaults to "ui". */
  source?: "ui" | "cli";
};

export type QueryApi = {
  /**
   * Streams the run as it happens. Failing SQL is *not* an HTTP error — it arrives as an `error`
   * event followed by `done`; only a bad request (unknown connection, empty sql) rejects.
   * Breaking out of the loop closes the body, which the server reads as a cancel.
   */
  run(input: RunInput, opts?: CallOptions): AsyncIterable<RunEvent>;
  /** The same run, awaited: one JSON reply once every statement has finished. */
  runSync(input: RunInput, opts?: CallOptions): Promise<RunRecord>;
};

export function queryApi(http: Transport): QueryApi {
  async function* run(input: RunInput, opts: CallOptions = {}): AsyncGenerator<RunEvent> {
    const response = await http.send("/api/query", {
      method: "POST",
      body: input,
      accept: "application/x-ndjson",
      signal: opts.signal,
    });
    if (!response.body) return; // only reachable behind a fetch implementation that buffers
    yield* readNdjson<RunEvent>(response.body, opts.signal);
  }

  return {
    run,
    runSync: (input, opts) =>
      http.json<RunRecord>("/api/query/sync", {
        method: "POST",
        body: input,
        signal: opts?.signal,
      }),
  };
}
